travis:
  secure:
    BINSTAR_TOKEN: es8A7C9cD/T9kAcne6Iy29hE14j2KkCIVcoLBUKuXkSeOFl0pKFfPLodQlH8ziG9VP5dml9SoI9FkAUe4XqjoUAiBOHeDuUV5rwFL79sApf6plQzTDAnSKA3bzAfMwY3tj65Y6jI4cnQXBK5sRCwMJp/P+NPt+QTVUiyWajjOYcvykQX9GD13OK9StjXj+pFfYW7cmHrXTfYu7zm8KiwmQtuQ5KO+NjEZu4GSasIoq5Q1BMzC8DrsDE4nONGJef1LoWmC1l9GHqoq6p2j32KYeSoE+IN7XCPuv4/bsrFfO1GIIxm8En68pU71L3TVvdZ67Kq5W4+dO3UeCErMmXuafjU0xpcA5zwSk79tNzYyNNEO4kgXy6pqs4Zwe23kKA4M9727EEpult1eED43UsbVzCWYFEKUtwAIwAg7L6s3eRZKPv1kc1vUd/W/NT+F+NM0TwpWAGKpRWV/pxaYyHiLFoUuTPtqzKIantxfb1eKTcMh6DbzVhnbu8p/jDOJw26v8rRVPW+fNBhTEWg6UYo4q5dDCDNXAffoHBiOVwbGWTzG7WFbQPmUGW6H4GJ4C9ooxnRxSnRenOVU5qUE9tfrlAiWrHXtuldQEteZ2QHRyfOplR/XLVlssRxrEBCei9/3m06wnCSIEmUZd4nN5mQhpLAF2F0/wE1RZb767oE86k=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
